### ISSUE TITLE
Fixed header covers frequency

### ISSUE THREAD

**Issue by Ivorytwelve** [Kagu-chan/jpdb.io#149]
![NZ6CIB3s7w](https://github.com/Kagu-chan/jpdb.io/assets/118703097/8c51ad66-d550-4b17-bdf7-4d116855ed0d)

The anime frequency gets covered by the header if a word appears in many frequency lists.

**Comment by Kagu-chan** [comment]
Thanks for reporting, I’ll look into it

**Comment by Kagu-chan** [comment]
Until a fix is available, you can adjust it with custom CSS:
```css
.vocabulary-list .tag { z-index: 9999; }
```
