### ISSUE TITLE
Overlay Menüs are seethrough

### ISSUE THREAD

**Issue by Kagu-chan** [Kagu-chan/jpdb.io#151]
See screenshot

![image](https://github.com/Kagu-chan/jpdb.io/assets/4511614/4444d234-38ce-478a-8f75-71d3cda33840)

**Comment by JaiWWW** [comment]
caused by the "Fix header navigation" setting

**Comment by Kagu-chan** [comment]
CSS z-Index probably overwritten. Caused through last fix on those properties
