### ISSUE TITLE
Blank target sentence cards with japanese names

### ISSUE THREAD

**Issue by noxxid3** [Kagu-chan/jpdb.io#77]
Is there an option to have here for name cards? I had a few show up but just disappeared on the review section since no sentence card existed.

**Comment by Kagu-chan** [comment]
I have to enable names and review one to see what happens.
Can you disable the TSC option and send me a screenshot of any name review?

**Comment by Kagu-chan** [comment]
Besides that, this is in general a known bug for TSC when there is no sentence. I have it on the radar to fix it.

**Comment by Kagu-chan** [comment]
Hi  @noxxid3 
Sorry for the late reply
The bug is fixed and will be released with the next main release. I cant tell now when this will be, but with this a lot of stuff will get improved
